### ISSUE TITLE
Fix communication between server and client

### ISSUE THREAD

**Issue by jjarzbach** [monsieur-x/android-app#32]
Communication between the server's develop branch and the android-app's conn/connection branch does't work properly because the conn/connection branch is based on an outdated version of the data models.
Rebase the conn/connection branch to include the current version of the data models should solve the communication issue.

**Comment by likesmusik** [comment]
cherry picked https://github.com/monsieur-x/android-app/commit/2a06384d3618f42144a70b6b45a4fdba9e262a37
